# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c069ae96e5678427587d7412a36029b3fed771200ae9a74c155ed530826d3b8a13945bf5a399e5d9990541500b0f1593527a00a2bedb3fc5ee5249f3d15930c5

test:
  secret_key_base: a9f2cdefa01797260ee0f044c3c634865faf9b7ebff6847f65a393616cd483b1eb4104d2f2f6b71ddcfb2c7cacb37d0d63a9c58c94af8b696aa86b9c105de3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
